### PR TITLE
Tests/standardise assertions pt4

### PR DESCRIPTION
**Pull request by Rosalita**
More work completed towards #456

### CODE REVIEW

**Comment by Morganamilo** [comment]
I see and have been seeing so many work in progress commits. I'd generally consider that bad and messy. Is there a reason it's not just one commit? Or multiple commits with better tittles?

**Comment by Rosalita** [comment]
> I see and have been seeing so many work in progress commits. I'd generally consider that bad and messy. Is there a reason it's not just one commit? Or multiple commits with better tittles?

It's usually because I have had to change tasks and want to save my progress. Would you like me to rebase and squash them all into just 1 commit to reduce the noise in the commit history?

**Comment by mohyour** [comment]
> 

You can create a commit before switching, then update that commit when you're back on the task.

**Comment by Morganamilo** [comment]
> It's usually because I have had to change tasks and want to save my progress. Would you like me to rebase and squash them all into just 1 commit to reduce the noise in the commit history?

that's what i always do.  `git rebase -i main`

**Comment by Morganamilo** [comment]
For wip commits i just --ammend over it.

**Comment by Rosalita** [comment]
I've squashed everything into 1 commit.

**Review by Morganamilo — APPROVED** [review]

**Review by mohyour — APPROVED** [review]

**Pull request merged**
