### PR TITLE
Use modules to remove vendored websocket library

### PR DESCRIPTION
**Pull request by paddybyers**
@gernest Should this commit include `go.mod` ?

### CODE REVIEW

**Comment by gernest** [comment]
@paddybyers yes, `go.mod` should be included

**Comment by paddybyers** [comment]
@gernest final question: is there anything we should add to the README to indicate that this is now set up to use modules? Does it affect usage in any way?

**Comment by gernest** [comment]
@paddybyers nope, this is backward compatible. Although the ones using go modules will benefit the most. The installation process using `go get` will work for both go modules and old go versions ( The one we already support)

**Comment by paddybyers** [comment]
ok, thanks

**Pull request merged**
