### PR TITLE
Auth API changes

### PR DESCRIPTION
**Pull request by rjeczalik**

### CODE REVIEW

**Comment by kouno** [comment]
We will probably merge the Auth changes tomorrow, so I'll just wait until then. You should work on top of this branch in the meantime.

**Comment by mattheworiordan** [comment]
Looks good

**Comment by rjeczalik** [comment]
I'm going to switch env to sandbox in separate PR - right now I'm getting `{"code": 40101, "message": "No key id specified"}` for `/token` requests.

**Comment by rjeczalik** [comment]
@kouno Hey can we have this merged or there something more that needs to be done for this PR?

**Comment by kouno** [comment]
No that looks good. We have not pushed the latest changes to sandbox/production yet, but I'll merge it anyway.

:ship: :ship: :ship:

**Comment by rjeczalik** [comment]
Thanks! The tests are still executed against staging, so there should be no problem for now.

**Pull request merged**
