### PR TITLE
Data sent as []byte should be decoded as []byte

### PR DESCRIPTION
**Pull request by amnonbc**
Fixes https://github.com/ably/ably-go/issues/574

The spec states:

[(RSL6a)](https://sdk.ably.com/builds/ably/specification/main/features/#RSL6a) All messages received will be decoded automatically based on the encoding field and the payloads will be converted into the format they were originally sent using i.e. binary, string, or JSON

In this case the message was sent as []byte so should have been received as as []byte.

This PR fixes the behaviour when receiving a `[]byte` message.

The problem is that merging this PR could cause user code to panic at runtime, if it assumes the old incorrect behaviour 
and does something like

`payload := msg.Data.(string)`

Is this a breaking change which requires a new major version?
How many customers are using ably-go to receive realtime messages? 
The SDK team will need to decide.

### CODE REVIEW

**Review by sacOO7 — CHANGES_REQUESTED** [review]
Can you add one more msgpack integration test that sends binary data and checks on another side if data is received in the required format?

**Comment by amnonbc** [comment]
> Can you add one more msgpack integration test that sends binary data and checks on another side if data is received in the required format?

done in  68c0afe

**Comment by sacOO7** [comment]
Are we waiting for anymore changes on this PR? I remember there was issue the msgpack library for encoding/decoding data?

**Comment by amnonbc** [comment]
> Are we waiting for anymore changes on this PR? I remember there was issue the msgpack library for encoding/decoding data?

Yes, I am adding some more fixture tests. Should be done by the end of the weekend.

But the SDK team will need to discuss what we do with this PR, as it will break current behaviour (see PR comment).

**Comment by amnonbc** [comment]
I am going to close this for now as it is a breaking change, which will cause currently working code to panic at runtime.
This change is too small to justify a v2 api on its own. So I will close the PR for now, but link it to the bug, as an example of how the bug can be fixed when the SDK team does a v2.

**Pull request closed without merging**
