### PR TITLE
Documentation improvements for RealtimePresence.

### PR DESCRIPTION
**Pull request by Rosalita**
While building my demo project, I hit a snag with using `RealtimePresence.Enter()` without a ClientID. @owenpearson was kind enough to explain to me how this functionality worked. This PR adds two godoc examples to the code base. One for `Enter` and one for `EnterClient`. 

I'm also updating the comment for `RealtimePresence.Get` which says a channel must be attached as I found this statement to be untrue while working on my demo.

I've also added a go.pkg.dev badge to the project readme file as this will prevent developers having to google to find package documentation.

Summary of this PR:
- Godoc examples for `RealtimePresence.Enter` and `RealtimePresence.EnterClient` have been added.
- Inaccurate code comment for `RealtimePresence.Get` updated for accuracy.
- A badge linking to the go.pkg.dev reference page for ably-go has been added to the project readme file.

### CODE REVIEW

**Review by lmars — APPROVED** [review]
LGTM

**Review by QuintinWillison — APPROVED** [review]
Relates to https://github.com/ably/ably-go/issues/347, as I would like to see preview of docs output from PRs at some point.

**Comment by Rosalita** [comment]
> Relates to #347, as I would like to see preview of docs output from PRs at some point.

If you would like to preview this documentation locally on your machine it's possible with the following steps:
1. Clone `ably-go` repo and check out branch `godocs`
2. Run the following command in terminal to get godoc `go get golang.org/x/tools/cmd/godoc`
3. Navigate to the root directory of the project and type `godoc` into the terminal window.
4. In a browser, navigate to `http://localhost:6060` to see your local version of godoc documentation.

Hope this helps.

**Comment by QuintinWillison** [comment]
@Rosalita and I have also discussed this via Slack DMs. I've pointed out that the `godoc` command output she's detailed doesn't solve the problem I would like to solve in #347, which is to have HTML static output pushed to our own S3 bucket showing us a preview of the documentation for the branch underlying any specific PR. Akin to what we do [here](https://github.com/ably/ably-asset-tracking-android/blob/main/.github/workflows/docs.yml) in AAT.

There is also [this internal Slack thread](https://ably-real-time.slack.com/archives/C0114KK7S6R/p1623922381097100) with @lmars from earlier last year.

**Pull request merged**
